"""Fix verifie column default value

Revision ID: a5d0d4593d5f
Revises: 
Create Date: 2025-02-07 20:25:31.963815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a5d0d4593d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_trainer')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image')

    op.create_table('_alembic_tmp_trainer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('experience', sa.INTEGER(), nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('availability_schedule', sqlite.JSON(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('ratings', sa.FLOAT(), nullable=True),
    sa.Column('aadhaar_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pan_card_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('verifie', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
